import Head from 'next/head'
import Image from 'next/image'
import { checkout } from '../checkout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Buy my carts
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Image src="/images/desktop.jpg" alt="image" width={600} height={400} />
            <p>Very expensive item 1</p>
            <button onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1LIsg8SEz6UhTNkybvJdN6aK",
                    quantity: 1
                  }
                ]
              })
            }}>BUY!</button>
          </div>
          <div className={styles.card}>
            <Image src="/images/front-picture.jpg" alt="image" width={600} height={400} />
            <p>Very expensive item 2</p>
          </div>
        </div>
      </main>
    </div>
  )
}
